Simplify local editable package in pyproject.toml
Simply specify the path to the local editable package.
Also attempts to a fix a TOML parsing error when trying
to deploy a streamlit app:

error: Failed to parse: `pyproject.toml`
Caused by: TOML parse error at line 18, column 34
...
18 | espn-league54078-fantasy-stats = { workspace = true, editable = true }
...
cannot specify both `index` and `editable`